apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: connect-redis
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/baffwuah77/connect-redis-argocd.git
    targetRevision: main
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: connect-redis
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
